# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_drop_subscription_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="social_login_bdren_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usersocialaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("github", "GitHub"),
                    ("bdren", "BdREN"),
                ],
                max_length=20,
            ),
        ),
    ]
