# Generated by Django 4.2.10 on 2026-05-07 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("accounts", "0008_add_bdren_social_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="opsync_role",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("supervisor", "Supervisor"),
                    ("line_manager", "Line Manager"),
                    ("admin_officer", "Admin Officer"),
                    ("am_dm", "AM/DM (Admin)"),
                    ("finance_officer", "Finance Officer"),
                    ("system_admin", "System Admin"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
    ]
