# Generated by Django 4.2.10 on 2026-05-08 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("capacity", models.PositiveIntegerField()),
                ("equipment", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="MeetingBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference_number", models.CharField(max_length=30, unique=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("attendee_count", models.PositiveIntegerField()),
                ("has_external_attendees", models.BooleanField(default=False)),
                ("external_attendee_notes", models.TextField(blank=True)),
                ("equipment_requested", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="meetings.meetingroom",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "date", "status"],
                        name="meetings_me_room_id_5fa9c6_idx",
                    ),
                    models.Index(
                        fields=["requester", "date"],
                        name="meetings_me_request_24066e_idx",
                    ),
                ],
            },
        ),
    ]
