# Generated by Django 4.2.10 on 2026-05-08 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0002_seed_board_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingbooking",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meetingbooking",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_meeting_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
